# Site settings
title: Woolf Official Website # site title
description: >- # site description
  This is the official page of the Woolf video game developer.
lang: en-US # default lang
timezone: Europe/Spain # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Woolf Von Byron # author name
  bio: >- # author bio
    Game Developer | Indie Game Developer | Game Designer | Game Programmer | Pixel Artist
  username: WoolfDev # general username
  github: WoolfDeveloper # github username
  twitter: @WoolfDev # twitter username
  instagram: @woolf.css # instagram username
  email: lluclanser@gmail.com # email address
  avatar: /assets/img/Woolficon.png # avatar image

# URL settings
url: "https://woolfgamedev.com"
baseurl:
permalink: /
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
